/*--------------------------------------------------------------
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * See License.txt in the project root for license information.
 *--------------------------------------------------------------*/

import CheckoutPaymentInstrument from './wc-checkout-payment-instrument';
import CheckoutPaymentInstrumentView from './wc-checkout-payment-instrument.view';

export * from './actions/get-card-payment-accept-point';
export * from './wc-checkout-payment-instrument';
export * from './wc-checkout-payment-instrument.data';
export {
    IWcCheckoutPaymentInstrumentConfig,
    IWcCheckoutPaymentInstrumentProps,
    IWcCheckoutPaymentInstrumentResources
} from './wc-checkout-payment-instrument.props.autogenerated';
export * from './wc-checkout-payment-instrument.view';
export * from './components';

export { CheckoutPaymentInstrument, CheckoutPaymentInstrumentView };
